### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [konarlook/Auth_sprint_1#55]
Несколько рекомендаций:
1. Давайте [трейсер](https://github.com/konarlook/Auth_sprint_1/blob/e433aa8413fd661a121ef687e0203f6c4ec4bc10/auth/src/main.py#L27-L31) занесем под `if settings.enable_tracer`, чтобы была возможность его отключить в тех же тестах
2. [Это](https://github.com/konarlook/Auth_sprint_1/blob/e433aa8413fd661a121ef687e0203f6c4ec4bc10/auth/src/main.py#L60) лишнее.
3. [Эти значения](https://github.com/konarlook/Auth_sprint_1/blob/e433aa8413fd661a121ef687e0203f6c4ec4bc10/auth/src/main.py#L77-L79), как правило, держат в переменных окружения. Как и все остальные значения, которые могут быть изменены в процессе работы
4. Попробуйте команду `flake8 auth --exclude auth/src/migrations --max-line-length 120 --count`. Меня отругала 16ю ошибками
5. Не смог найти задание про ограничение количества запросов. Можно использовать и готовые решения. Например, https://github.com/long2ice/fastapi-limiter
6. Уточните, у вас ролями кажется могут управлять все авторизованные пользователи. 
7. [можно лучше] Кстати, создание админа в миграциях, как это делаете вы, возможно, но не оптимально. Удобнее будет создание консольной команды https://typer.tiangolo.com/
8. А для проверки прав пользователя можно создать декоратор, который будет доставать токен из заголовка запроса и принимать решение о допуске пользователя к эндпоинту. Вот тут может быть что-то покажется интересным в этой связи https://gist.github.com/RomanAVolodin/e2731b303ef8b3c29d1052e82d5a7b36
9. Имена провайдеров (google, yandex и т.д.) лучше поместить в enum. Работа с литералами - всегда не очень хорошая практика. Далее с развитием проекта может возникнуть необходимость их использовать в коде. Работа с enum, как минимум, избавит нас от опасности опечатки.
10. [Этот метод](https://github.com/konarlook/Auth_sprint_1/blob/e433aa8413fd661a121ef687e0203f6c4ec4bc10/app/movies/auth_backend.py#L18) бросается исключениями если не может достучаться до хоста назначения. Исключение нужно поймать и обработать.
![282288183-79202d49-15c2-4542-ba8e-e7e9bb4ecd24-5](https://github.com/konarlook/Auth_sprint_1/assets/73478414/43c7a217-91a4-4059-931c-de44dfae3230)

**Comment by BigDeepBlue** [comment]
Ловко решили проблему п.п. 6-8 **добавив декоратор**. Сейчас все еще **ЛЮБОЙ** авторизованный пользователь может сделать себя админом.

**Comment by konarlook** [comment]
> Ловко решили проблему п.п. 6-8 **добавив комментарий к декоратору** 😀, который там уже и был. Сейчас все еще **ЛЮБОЙ** авторизованный пользователь может сделать себя админом.

Я немного не понимаю. Этот же декоратор проверяет валидность токенов + проверяет список экшенов, который присущ данной роли у данного юзера

**Comment by konarlook** [comment]
![image](https://github.com/konarlook/Auth_sprint_1/assets/103597904/2c379eba-9809-4abb-bf2f-2f482986a5d1)

**Comment by BigDeepBlue** [comment]
Ааааааааа! Увидел. 
Я не ожидал, что в  вашей функции `is_token_expired` совершенно неожиданно проверяются пермишены.
